name: Build Sample

on: [push, pull_request]

jobs:
  build-win:
    name: Build for Windows UWP
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x64]
        target: [WindowsStore]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: df270daa8d6d48426e128e50c73357dfdf89afbf
          submodules: true

      - name: Configure
        run: cmake -DCMAKE_SYSTEM_NAME=${{ matrix.target }} -DCMAKE_SYSTEM_VERSION="10.0" -A${{ matrix.arch }} -S . -B build

      - name: Build
        run: cmake --build build --target sdl-min --config Release

      - name: Generate Self-Signed Certificate
        id: generate_cert
        run: |
          $cert = New-SelfSignedCertificate -CertStoreLocation "Cert:\CurrentUser\My" -Subject "CN=MyUWPCert" -KeyAlgorithm RSA -KeyLength 2048 -Provider "Microsoft Enhanced RSA and AES Cryptographic Provider" -KeyExportPolicy Exportable -NotAfter (Get-Date).AddYears(1) -Type CodeSigningCert
          echo "THUMBPRINT=$($cert.Thumbprint)" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Export and Reimport Certificate
        run: |
          $cert = Get-ChildItem -Path "Cert:\CurrentUser\My" | Where-Object { $_.Thumbprint -eq "$env:THUMBPRINT" }
          if ($cert) {
            Export-Certificate -Cert $cert -FilePath $env:USERPROFILE\MyUWPCert.cer
            Import-Certificate -FilePath $env:USERPROFILE\MyUWPCert.cer -CertStoreLocation "Cert:\LocalMachine\TrustedPeople"
          }
        shell: pwsh

      - name: Set Package Name
        id: set_package_name
        run: |
          echo "PACKAGE_NAME=${{ github.event.inputs.package_name }}_${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
        shell: pwsh

      - name: Add Signtool Action
        uses: KamaranL/add-signtool-action@v1
        with:
          certThumbprint: ${{ env.THUMBPRINT }}
          msixPath: D:\a\SDL3-uwp\SDL3-uwp\build\AppPackages\sdl-min\sdl-min_1.0.0.0_x64_Test\sdl-min_1.0.0.0_x64.msix
          timestampUrl: http://timestamp.digicert.com

      - name: Archive MSIX Package
        run: |
          Compress-Archive -Path build/AppPackages/sdl-min/**/*.msix -DestinationPath build/AppPackages/sdl-min-${{ matrix.target }}-${{ matrix.arch }}.zip
        shell: pwsh

      - name: Upload MSIX Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdl-min-${{ matrix.target }}-${{ matrix.arch }}
          path: build/AppPackages/sdl-min-${{ matrix.target }}-${{ matrix.arch }}.zip
