name: Build Sample
on: [push, pull_request]

jobs:
    build-win:
        name: Build for Windows UWP
        runs-on: windows-latest
        strategy:
          fail-fast: false
          matrix:
              arch: [x64]
              target: [WindowsStore]

        steps:
          - uses: actions/checkout@v4
            with:
             ref: df270daa8d6d48426e128e50c73357dfdf89afbf
             submodules: true
          - name: Configure
            run: cmake -DCMAKE_SYSTEM_NAME=${{ matrix.target }} -DCMAKE_SYSTEM_VERSION="10.0" -A${{ matrix.arch }} -S . -B build
          - name: Build
            run: cmake --build build --target sdl-min --config Release
          - name: Upload Build
            uses: actions/upload-artifact@v4
            if: ${{ matrix.target != 'WindowsStore' }}
            with: 
                name: sdl-min-${{ matrix.target }}-${{ matrix.arch }}
                path: |
                    build/Release/*.msix
