name: Sign MSIX Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download PackageRe-Sign Tool
        run: |
          Invoke-WebRequest -Uri "https://github.com/Empyreal96/Appx_Re-Sign/releases/download/1.1.1.0/PackageRe-Sign.Release.zip" -OutFile "PackageRe-Sign.Release.zip"
          Expand-Archive -Path "PackageRe-Sign.Release.zip" -DestinationPath "PackageRe-Sign (Release)"

      - name: Run the batch file to sign the MSIX package
        run: |
          # Ensure the MSIX file and output folder paths are correctly set
          $msixFilePath = "$env:GITHUB_WORKSPACE\sdl-min_1.0.0.0_x64.msix"
          $outputFolder = "$env:GITHUB_WORKSPACE\output"
          
          # Set the path to the PackageRe-Sign folder where pkgrsn.exe is located
          $pkgrsnPath = "$env:GITHUB_WORKSPACE\PackageRe-Sign (Release)"
          
          # Escape the path to pkgrsn.exe properly for PowerShell
          $pkgrsnExe = "$pkgrsnPath\pkgrsn.exe"
          
          # Use the Start-Process cmdlet to invoke pkgrsn.exe with the correct arguments
          Start-Process -FilePath $pkgrsnExe -ArgumentList "`"$msixFilePath`", `"$outputFolder`""

      - name: Upload the signed MSIX as artifact
        uses: actions/upload-artifact@v4
        with:
          name: signed-msix
          path: output/sdl-min_1.0.0.0_x64.msix
