name: MSIX Signing

on:
  push:
    branches:
      - main

jobs:
  sign-msix:
    runs-on: windows-latest
    
    steps:
      # Step 1: Checkout the code repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install PowerShell module for certificate creation
      - name: Install PowerShell module
        run: Install-Module -Name PSScriptTools -Force -Scope CurrentUser

      # Step 3: Generate self-signed certificate using PowerShell
      - name: Generate self-signed certificate
        run: |
          # Generate the self-signed certificate
          $cert = New-SelfSignedCertificate -CertStoreLocation Cert:\CurrentUser\My -DnsName "CN=Ravbug" -KeyAlgorithm RSA -KeyLength 2048 -NotAfter (Get-Date).AddYears(1)
          
          # Export the certificate to .pfx format for later usage in signing
          Export-PfxCertificate -Cert $cert -FilePath "$env:GITHUB_WORKSPACE\certificate.pfx" -Password (ConvertTo-SecureString -String "yourpassword" -Force -AsPlainText)
        shell: pwsh

      # Step 4: Set paths for MSIX and certificate
      - name: Set paths for MSIX and certificate
        run: |
          $msixFilePath = "$env:GITHUB_WORKSPACE\sdl-min_1.0.0.0_x64.msix"
          $outputFolder = "$env:GITHUB_WORKSPACE\signed_output"
          $certificatePath = "$env:GITHUB_WORKSPACE\certificate.pfx"
          echo "MSIX file path: $msixFilePath"
          echo "Output folder: $outputFolder"
          echo "Certificate path: $certificatePath"
        shell: pwsh

      # Step 5: Unpack the MSIX file in Visual Studio Developer Command Prompt
      - name: Unpack MSIX file using VS Dev Command Prompt
        shell: pwsh
        run: |
          # Launching Visual Studio Developer Command Prompt to set the environment
          $vsDevCmd = "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VsDevCmd.bat"
          
          # Run MakeAppx inside the developer command prompt
          Start-Process -FilePath $vsDevCmd -ArgumentList "/c MakeAppx unpack /p $env:GITHUB_WORKSPACE\sdl-min_1.0.0.0_x64.msix /d $env:GITHUB_WORKSPACE\unpacked" -Wait
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}

      # Step 6: Sign the MSIX package
      - name: Sign MSIX package
        shell: pwsh
        run: |
          # Full path to SignTool
          $signToolPath = "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\signtool.exe"
          $msixFilePath = "$env:GITHUB_WORKSPACE\sdl-min_1.0.0.0_x64.msix"
          
          # Sign the MSIX package using the .pfx certificate
          Start-Process -FilePath $signToolPath -ArgumentList "sign /f $env:GITHUB_WORKSPACE\certificate.pfx /p yourpassword /t http://timestamp.digicert.com /v $msixFilePath" -Wait

      # Step 7: Upload the signed MSIX
      - name: Upload signed MSIX
        uses: actions/upload-artifact@v4
        with:
          name: signed-msix
          path: ${{ github.workspace }}/sdl-min_1.0.0.0_x64.msix
