name: MSIX Signing

on:
  push:
    branches:
      - main

jobs:
  sign-msix:
    runs-on: windows-latest
    
    steps:
      # Step 1: Checkout the code repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install PowerShell module for certificate creation
      - name: Install PowerShell module
        run: Install-Module -Name PSScriptTools -Force -Scope CurrentUser

      # Step 3: Generate self-signed certificate using PowerShell
      - name: Generate self-signed certificate
        run: |
          # Generate the self-signed certificate
          $cert = New-SelfSignedCertificate -CertStoreLocation Cert:\CurrentUser\My -DnsName "CN=Ravbug" -KeyAlgorithm RSA -KeyLength 2048 -NotAfter (Get-Date).AddYears(1)
          
          # Export the certificate to .cer (certificate) format for later usage in signing
          Export-Certificate -Cert $cert -FilePath "$env:GITHUB_WORKSPACE\certificate.cer"
        shell: pwsh

      # Step 4: Set paths for MSIX and certificate
      - name: Set paths for MSIX and certificate
        run: |
          $msixFilePath = "$env:GITHUB_WORKSPACE\sdl-min_1.0.0.0_x64.msix"
          $certificatePath = "$env:GITHUB_WORKSPACE\certificate.cer"
          echo "MSIX file path: $msixFilePath"
          echo "Certificate path: $certificatePath"
        shell: pwsh

      # Step 5: Sign the MSIX package using SignTool with the self-signed certificate
      - name: Sign MSIX package
        run: |
          # Full path to SignTool
          $signToolPath = "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\signtool.exe"
          $msixFilePath = "$env:GITHUB_WORKSPACE\sdl-min_1.0.0.0_x64.msix"
          
          # Sign the MSIX file using the self-signed certificate from the Cert store
          Start-Process -FilePath $signToolPath -ArgumentList "sign /s MY /n ""Ravbug"" /t http://timestamp.digicert.com /v $msixFilePath" -Wait
        shell: pwsh

      # Step 6: Upload signed MSIX file as artifact
      - name: Upload signed MSIX
        uses: actions/upload-artifact@v4
        with:
          name: signed-msix
          path: ${{ github.workspace }}/sdl-min_1.0.0.0_x64.msix
