name: Re-sign MSIX Package

on: [push, pull_request]

jobs:
  re-sign-msix:
    name: Re-sign MSIX Package
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Download PackageRe-Sign tool
      - name: Download PackageRe-Sign Tool
        run: |
          $url = "https://github.com/Empyreal96/Appx_Re-Sign/releases/download/1.1.1.0/PackageRe-Sign.Release.zip"
          $outputPath = "PackageRe-Sign.Release.zip"
          Invoke-WebRequest -Uri $url -OutFile $outputPath

      # Extract the downloaded ZIP file
      - name: Extract PackageRe-Sign Tool
        run: |
          Expand-Archive -Path PackageRe-Sign.Release.zip -DestinationPath .

      # Set the project path and package name
      - name: Set paths for the MSIX package and other required arguments
        run: |
          # Set the directory and MSIX file name
          $projectPath = "${{ github.workspace }}\msix"  # Folder containing the MSIX package
          $packageName = "sdl-min_1.0.0.0_x64.msix"  # MSIX package name
          $packagePath = Join-Path $projectPath $packageName  # Full path to MSIX file

          # Ensure output folder exists
          $outputFolder = Join-Path $projectPath "output"
          if (-not (Test-Path -Path $outputFolder)) {
              New-Item -ItemType Directory -Force -Path $outputFolder
          }

          # Set other arguments
          $outputPackageName = "sdl-min_1.0.0.0_x64.msix"  # Corrected output file name with .msix
          $publisher = "CN=Ravbug"  # Publisher name from the AppxManifest.xml
          $pfxFile = ""  # Default PFX file (not provided)
          $pfxPassword = ""  # Default PFX password (not provided)

          # Run pkgrsn to re-sign the MSIX package
          & ".\PackageRe-Sign (Release)\pkgrsn.exe" -a $packagePath -p $publisher -o $outputFolder -x $pfxFile -s $pfxPassword -k

      # Optionally, you can upload the signed package as an artifact
      - name: Upload Signed MSIX Artifact
        uses: actions/upload-artifact@v4
        with:
          name: signed-msix-package
          path: output/**/*.msix
