name: Sign MSIX Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download PackageRe-Sign Tool
        run: |
          Invoke-WebRequest -Uri "https://github.com/Empyreal96/Appx_Re-Sign/releases/download/1.1.1.0/PackageRe-Sign.Release.zip" -OutFile "PackageRe-Sign.Release.zip"
          Expand-Archive -Path "PackageRe-Sign.Release.zip" -DestinationPath "PackageRe-Sign (Release)"

      - name: Run the batch file to sign the MSIX package
        run: |
          # Ensure the MSIX file and output folder paths are correctly set
          $msixFilePath = "$(Build.SourcesDirectory)\sdl-min_1.0.0.0_x64.msix"
          $outputFolder = "$(Build.SourcesDirectory)\output"

          # Set the path to the PackageRe-Sign folder where pkgrsn.exe is located
          $pkgrsnPath = "$(Build.SourcesDirectory)\PackageRe-Sign (Release)"

          # Run the batch file to sign the MSIX package
          cd $(Build.SourcesDirectory)  # Go to the root directory where the .bat file is located
          .\sign_package.bat "$msixFilePath" "$outputFolder" "$pkgrsnPath"

      - name: Upload the signed MSIX as artifact
        uses: actions/upload-artifact@v4
        with:
          name: signed-msix
          path: output/sdl-min_1.0.0.0_x64.msix
