name: Sign MSIX Package

on:
  workflow_dispatch:

jobs:
  sign-msix:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download PackageRe-Sign Tool
        run: |
          Invoke-WebRequest -Uri "https://github.com/Empyreal96/Appx_Re-Sign/releases/download/1.1.1.0/PackageRe-Sign.Release.zip" -OutFile "PackageRe-Sign.Release.zip"
          Expand-Archive -Path "PackageRe-Sign.Release.zip" -DestinationPath "PackageRe-Sign"

      - name: Ensure correct paths
        run: |
          $msixFilePath = "$env:GITHUB_WORKSPACE\sdl-min_1.0.0.0_x64.msix"
          $outputFolder = "$env:GITHUB_WORKSPACE\signed_output"
          $pkgrsnExe = "$env:GITHUB_WORKSPACE\PackageRe-Sign\PackageRe-Sign (Release)\pkgrsn.exe"
          
          # Verify file existence before running
          if (-Not (Test-Path $msixFilePath)) { Write-Error "ERROR: MSIX file not found!" ; exit 1 }
          if (-Not (Test-Path $pkgrsnExe)) { Write-Error "ERROR: pkgrsn.exe not found!" ; exit 1 }
          
          echo "MSIX File Path: $msixFilePath"
          echo "Output Folder: $outputFolder"
          echo "pkgrsn.exe Path: $pkgrsnExe"

          .\sign_package.bat "`"$msixFilePath`"" "`"$outputFolder`"" "`"$pkgrsnExe`""

      - name: Upload the signed MSIX as artifact
        uses: actions/upload-artifact@v4
        with:
          name: signed-msix
          path: signed_output/signed_sdl-min_1.0.0.0_x64.msix
